# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode9.3beta
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
  - bundle install # Since Travis is not always on latest version
  - pod install --project-directory=Example
script:
  #- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Proj.Swift.xcworkspace -scheme SwiftProjection -sdk iphonesimulator11.3 -destination "platform=iOS Simulator,OS=9.0,name=iPhone 6" ONLY_ACTIVE_ARCH=NO | xcpretty
  - set -o pipefail && pod lib lint --verbose | xcpretty
